### ISSUE TITLE
Wishlist: add GR-RFTAP to build

### ISSUE THREAD

**Issue by veso266** [pothosware/PothosSDR#34]
Hi do you think you could add gr-rftap to build?

gr-rftap: https://github.com/rftap/gr-rftap

gr-rftap info: https://rftap.github.io/

**Comment by guruofquality** [comment]
@veso266 thats reasonable. No complicated dependencies for this one, its just python: https://github.com/pothosware/PothosSDR/commit/e0e58ff56f7612b013038f78d80c2f10e73a3281

I will reply when the new installer is up

**Comment by guruofquality** [comment]
PothosSDR-2016.09.08-vc14-x64.exe is up, should have rftap
