### ISSUE TITLE
Include Inspectrum

### ISSUE THREAD

**Issue by watkipet** [pothosware/PothosSDR#41]
Many Linux and macOS users use baudline for analyzing SDR recordings, however its source re-distribution policy is restrictive. [Inspectrum](https://github.com/miek/inspectrum) is an alternative and also uses cmake for its build environment. It requires:

* fftw - (already in PothosSDR)
* liquid-dsp (already in PothosSDR)
* qt5 (already in PothosSDR)
* mman-win32

Please consider adding Inspectrum so users can easily view SDR dumps.

**Comment by guruofquality** [comment]
Cool, it does seem like a good fit.

* I will have to see about mman-win32 as far as building or downloading it.

* Also, liquid-dsp is currently only in CubicSDR as a binary. I want to change that anyway for PothosLiquidDSP toolkit, but I will have to figure out how to build it somehow, or copy the Cubic one :-) 

* Licensing seems to be GPL3, which is basically inline with half of the software already in here
