### ISSUE TITLE
Updating SoapySDR to 0.7

### ISSUE THREAD

**Issue by jlobingier** [pothosware/PothosSDR#55]
I built my Windows system with "PothosSDR-2018.04.26-vc14-x64.exe " which installed support for the 0.6 Lib version.  How do I update this install to support 0.7?

Thank you,

Jack

**Comment by guruofquality** [comment]
You can manually build SoapySDR master branch + whatever modules you need. And install over the c:\program files\PothosSDR directory (use the same CMAKE_INSTALL_PREFIX)

Or if you are building PothosSDR, you can change this line to master: https://github.com/pothosware/PothosSDR/blob/master/BuildSoapySDR.cmake#L22

PS The 0.7 stuff is the currently unreleased master branch? Is there a particular feature you are looking that missing in the 0.6 API?

**Comment by guruofquality** [comment]
Version with soapy0.7 up
