### ISSUE TITLE
Long timeouts and ERROR: Unable to find host: No such host is known.

### ISSUE THREAD

**Issue by guruofquality** [pothosware/PothosSDR#56]
_From @vsboost on July 14, 2018 6:6_

Just wondering why i get these errors continuously, and if there is something i can do to make them stop.

Thanks

![image](https://user-images.githubusercontent.com/11001973/42721548-c58371c2-877f-11e8-9759-9b458de20e30.png)

_Copied from original issue: pothosware/PothosFlow#165_

**Comment by guruofquality** [comment]
@vsboost @asymcon Its the new support for pluto sdr, you can delete C:\PothosSDR\lib\SoapySDR\modules0.6\PlutSDRSupport.dll in the meantime

**Comment by guruofquality** [comment]
I tracked it down to the SoapyPlutoSDR project. I think its doing network things it should not: https://github.com/jocover/SoapyPlutoSDR/issues/3

**Comment by vsboost** [comment]
Thanks for this.

**Comment by guruofquality** [comment]
It also seems UHD is taking a very long time in this build due to some new module support (so its not helping things either). I gave them some patches: https://github.com/EttusResearch/uhd/issues/197

I'm also adding something similar to SoapySDR so modules can be searched for devices in parallel.

**Comment by guruofquality** [comment]
I patched the SoapyPlutoSDR for now to use a network address in the args and to not search for non existent default devices. I hope the patch makes it upstream
