### ISSUE TITLE
Can't find GrOsmo source and sink for Bundled GNURadio + GrOsmoSDR

### ISSUE THREAD

**Issue by dcmk1mr2** [pothosware/PothosSDR#58]
Everything in suite installed, ran Zadig, and everything seems to work.  GQRX works with several devices.  I just can't find the GrOsmo source/sink.  GRC works otherwise.

It must be right in front of me  - where is it?

Flow looks interesting - thanks for the cool software.

**Comment by guruofquality** [comment]
do you see it if you type ctrl + f and type osmo?

**Comment by dcmk1mr2** [comment]
Found it - TNX
