### ISSUE TITLE
GnuRadio bundled problem

### ISSUE THREAD

**Issue by pietro62** [pothosware/PothosSDR#63]
Hello,
Just installed PothosSDR (latest 2019 version)  with bundled Gnuradio on Win7-x64, I5 class machine (actually try 2 different machines and different USB SDR hardware SDRplay RSP1 and RSP2).

Very surprising, all went ok and both hardware work just fine on PothosFlow, CubicSDR and GQRX.
Only problem with bundled Gnuradio: a very basic test with an Osmocom source (soapy=1,driver=sdrplay) connected to a WX FFT sink, fail to show anything on FFT! No error messages, FFT sink window pop-up just fine but nothing elese. No signal from Osmocom source. Connecting a signal generato to the same FFT sink just work great. I try any possible config, SR, etc... no way.

Any suggestion please ?

![gnuradio](https://user-images.githubusercontent.com/46823251/52300860-423c0980-2989-11e9-889f-d58023ee34c4.JPG)

**Comment by guruofquality** [comment]
GQRX is also using the osmosdr source block. So if GQRX works, this is very unexpected. Can you double check that the arguments used to configure the device in GQRX are the same? device args, sample rate, etc?

**Comment by pietro62** [comment]
Hi guruofquality, thank you for fast answer .... well using version PothosSDR-2019.01.26-vc14-x64.
I've double - triple checked but nothing ! Is SoapySDRPlay bundled in GnuRadio ? I have only osmosdr block.  It's possible to check if osmocom module (soapy=1,driver=sdrplay) is streaming out some data ? 
Best regards ... Pietro


![gqrx](https://user-images.githubusercontent.com/46823251/52328380-b3aea300-29ef-11e9-8412-a989e215966d.PNG)

![gnuradio1](https://user-images.githubusercontent.com/46823251/52328396-bdd0a180-29ef-11e9-99e6-1e547fb1f144.PNG)

![gnuradio2](https://user-images.githubusercontent.com/46823251/52328402-c1fcbf00-29ef-11e9-835e-c6b9ace5af0e.PNG)

![programs](https://user-images.githubusercontent.com/46823251/52328444-ed7fa980-29ef-11e9-9356-c7d298340288.PNG)

**Comment by pietro62** [comment]
No errors ..... but nothing showing on FFT (or other sink ....)

![gnuradio3](https://user-images.githubusercontent.com/46823251/52328671-b78ef500-29f0-11e9-8468-3f19a9fed303.PNG)

**Comment by pietro62** [comment]
![read_file](https://user-images.githubusercontent.com/46823251/52346953-179d8f80-2a21-11e9-814f-97ad1c8d023a.PNG)

Just to confirm that all the rest is working OK (read a wav file at 5 Msps recorded with HDSDR).

**Comment by guruofquality** [comment]
It is streaming, you are just looking at zeros probably. Change your BB gain to under 10. This worked for me. Not sure why, have to ask the manufacturer. Maybe a safety squelch? Digital multiplier gone wrong?

**Comment by pietro62** [comment]
Wooowww !! I confirm it's just working great ! Now need just to start building some test flows ! Btw, what's the meaning of BB Gain ? thank you so much. Regards Pietro
