### ISSUE TITLE
Issue #63: work with SDRPlay RSP2 but not with RSP1

### ISSUE THREAD

**Issue by pietro62** [pothosware/PothosSDR#65]
Hi,

Tested solution to issue #63 (closed) and found working with hardware SDRPlay RSP2  but absolute nothing with RSP1 with the same API.

Need to found a definitive solution, maybe not using Soapy > Osmocom > hardware.
Maybe include in next version the HB9FXQ gr-sdrplay block (see https://www.sdrplay.com/docs/gr-sdrplay-workflow.pdf) that is a wrap directly to SDRPlay hardware, very often used.

Many thanks, Pietro

**Comment by guruofquality** [comment]
I have added gr-sdrplay to the build, it will be in the next installer. I passed the fixes onto the gitlab project: https://gitlab.com/HB9FXQ/gr-sdrplay/merge_requests/3
