### ISSUE TITLE
LimeSDR with 2020.01.04 CubicSDR crashes

### ISSUE THREAD

**Issue by v0l** [pothosware/PothosSDR#70]
Hi,

When trying to connect to LimeSDR (LimeSDR-USB FW:4 HW:4 Protocol:1 GW:2.21) CubicSDR and GQRX crash (Windows 10 X64)

Build from here: 
https://downloads.myriadrf.org/builds/PothosSDR/

**Comment by guruofquality** [comment]
Im seeing it too, the new setting options in limesuite seem to be causing a crash because deleting them fixes it.

**Comment by guruofquality** [comment]
Reported to limesuite: https://github.com/myriadrf/LimeSuite/issues/295

**Comment by guruofquality** [comment]
OK this will now be fixed in the next build
