### ISSUE TITLE
Wish List: Graph Header Page

### ISSUE THREAD

**Issue by dbnut** [pothosware/PothosSDR#72]
With other page tabs displayed below.
Highly useful in GRC, as various controls I need have cross-tab function.

**Comment by guruofquality** [comment]
I'm not sure what you mean, but there is an issue tracker for UI improvements: https://github.com/pothosware/PothosFlow/issues This is just the build script for the windows installer

**Comment by dbnut** [comment]
Thanks for that. I've created a new one as you advised. And explained myself better :).
