### ISSUE TITLE
Different report of uri value for same device

### ISSUE THREAD

**Issue by waterwin** [pothosware/PothosSDR#76]
I would expect both tools to present the same uri for the one Adalm Pluto device connected to my Windows10 on Oracle VM Virtual Boxon Windows10 host.

C:\Users\Erwin>SoapySDRUtil.exe --find
######################################################
######################################################

[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106700; UHD_3.15.0.0-0-gaea0e2de
Found device 0
  default_input = True
  default_output = True
  device_id = 0
  driver = audio
  label = Default Device

Found device 1
  default_input = False
  default_output = False
  device_id = 2
  driver = audio
  label = Microphone (High Definition Audio Device)

Found device 2
  device = plutosdr
  driver = plutosdr
  uri = usb:1.2.5 <<<<<

C:\Users\Erwin>iio_info -s
Library version: 0.21 (git tag: 565bf68)
Compiled with backends: xml ip usb serial
Unable to create Local IIO context : Function not implemented
Available contexts:
        0: 0456:b673 (Analog Devices Inc. PlutoSDR (ADALM-PLUTO)), serial=104x [usb:1.3.5 <<<<<<<<
        1: 192.168.2.1 (Analog Devices PlutoSDR Rev.B (Z7010-AD9364)), serial=104x [ip:pluto.local]

**Comment by guruofquality** [comment]
I will need some kind of pull request or issue reported: https://github.com/pothosware/SoapyPlutoSDR/issues I think at the end of the day, it just comes from the libiio library
