### ISSUE TITLE
[ERROR] Could not open hackrf device

### ISSUE THREAD

**Issue by ghost** [pothosware/PothosSDR#77]
Hi there!

Working on Elementary OS
`Linux uservb 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

I've got a Hackrf & Portapack. Now it's been turned to Hackrf One mode and the OS defines it as:
```
user@uservb:~$ hackrf_info 
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Board ID Number: 2 (HackRF One)
Firmware Version: git-ef5b907 (API:1.03)
Part ID Number: 0xa000cb3c 0x006a476b
```

All packages like `gnuradio hackrf gr-osmosdr libhackrf-dev libhackrf0` were installed successfully, SoapySDR & SoapyHackRF repos were compiled and installed without errors. 

Now I'm trying to run
`SoapySDRUtil -probe='driver=hackrf'`
```
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Probe device driver=hackrf
[INFO] Opening HackRF One #0 c83868dc2c1a70a3...
[INFO] Could not Open HackRF Device
Error probing device: hackrf open failed
```

What could cause that error?
Regards

**Comment by guruofquality** [comment]
Could be related to usb permissions maybe? Did you setup udev rules? Does it work with sudo? This is issue tracker is for the windows installer. If the hackrf utils are showing the issue `hackrf_info version: unknown` that probably related to the `hackrf open failed`, you really ought to contact the manufacturer or hackrf driver: https://github.com/mossmann/hackrf/wiki
