### ISSUE TITLE
SoapySDRUtil does not find LimeSDR

### ISSUE THREAD

**Issue by maristhek** [pothosware/PothosSDR#78]
Problem after installing PothosSDR/PothosSDR-2020.01.26-vc14-x64 on Windows SRV 2016 and Zadig installs WinUSB (v6.1.7600.16385) for LimeSDR-USB

C:\PothosSDR\bin>rtl_eeprom.exe
No supported devices found.

C:\PothosSDR\bin>SoapySDRUtil.exe --find
######################################################
######################################################

[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106700; UHD_3.15.0.0-0-gaea0e2de
Found device 0
  default_input = True
  default_output = True
  device_id = 0
  driver = audio
  label = Default Device

Found device 1
  default_input = False
  default_output = False
  device_id = 4
  driver = audio
  label = Digital Audio (S/PDIF) (2- High Definition Audio Device)

Please Advise.

**Comment by guruofquality** [comment]
Make sure the device shows up in the device manager and has the libusb device driver loaded (using zadig). Also it would be good to check lime's command line utils first. Does LimeUtil --find work for example
