### ISSUE TITLE
[Question] Pothos and Gnuradio 3.8

### ISSUE THREAD

**Issue by Radiomix2000** [pothosware/PothosSDR#79]
Is there planned update for Pothos SDR with gnuradio 3.8 included?

**Comment by feelingwalnut** [comment]
hopefully if dev releases a new build they can do it in an existing environment because i've spent a day just trying to set one up and good lord... nothing but vague errors and failed installs in python.

**Comment by guruofquality** [comment]
updated to gr3.9 https://github.com/pothosware/PothosSDR/pull/82
