### ISSUE TITLE
Complete GNU Radio + OsmoSDR installer

### ISSUE THREAD

**Issue by veso266** [pothosware/PothosSDR#9]
Hi Do you think you could add complete GNU Radio + OsmoSDR into Pothos installer?

I would like to use GNU Radio on windows and its a strugle to build everything from source

Thanks for Anwsering and Best Regards

PS: See here: https://pairlist9.pair.net/pipermail/hackrf-dev/2015-November/001632.html

**Comment by guruofquality** [comment]
@veso266 What do people generally prefer, gr-qtgui or gr-wxgui? wxgui is just a python dependency, which makes it easy to install. But one of the challenges is that the Qt blocks in GNU Radio use Qt4, whereas Pothos graphics are based around Qt5.

**Comment by veso266** [comment]
Hi I personally use gr-wxgui and I think that other people too so

Thanks again for making the installer

2015-11-21 2:02 GMT+01:00 Josh Blum notifications@github.com:

**Comment by guruofquality** [comment]
New installers are up, here are the docs: https://github.com/pothosware/PothosSDR/wiki/GNURadio
