### ISSUE TITLE
Question about future updates to PothosSDR Windows development environment

### ISSUE THREAD

**Issue by fventuri** [pothosware/PothosSDR#97]
@guruofquality - this is not really an issue, just a quick question.

A few days ago they told me about PothosSDR as a very easy way to install and run GNU Radio on Windows (I use Linux most of the time, and I am not really familiar with applications for Windows), so tonight I gave it a try, and I was able to install the latest version of PothosSDR on my Windows 10 computer (it's actually dual boot Linux/Windows) very quickly and without any problems (kudos Josh!)

I did notice that it installs GNU Radio 3.9.2 and the last commit was on 7/25/2021, so I was wondering if you had plans to release more up-to-date versions in the future, possibly with GNU Radio 3.10.x and newer versions of the OOT modules you built for Windows.

One of the reasons I am asking is because I noticed that the OOT module 'gr-sdrplay3' for SDRplay RSP devices distributed with PothosSDR has an older version of the files in the `maint-3.9` branch (https://github.com/fventuri/gr-sdrplay3/tree/maint-3.9); for instance we were having problems with the file `grc/sdrplay3_rspduo_block.yml` in PothosSDR, and for that file there were several commits that occurred after 7/25/2021 (https://github.com/fventuri/gr-sdrplay3/commits/maint-3.9/grc/sdrplay3_rspduo.block.yml).

Josh, thanks for all your hard work with PothosSDR and SoapySDR!

Franco

**Comment by ncorgan** [comment]
We're preparing for a large SoapySDR+Pothos update across the board, so expect this in a month or so.

**Comment by fventuri** [comment]
Thank for the update Nicholas!

**Comment by Heshyo** [comment]
@ncorgan Any updates? The _download installers_ on the wiki still points to https://downloads.myriadrf.org/builds/PothosSDR/ where the last build is from 2021.
